# dashboard.py
import json
import numpy as np
import os
import streamlit as st
from sentence_transformers import SentenceTransformer
from dotenv import load_dotenv

load_dotenv()

@st.cache_resource
def load_model():
    return SentenceTransformer(os.environ.get("EMBEDDING_MODEL_PATH", "C:/models/all-MiniLM-L6-v2"))

@st.cache_data
def load_data(file_path="all_chats_verified.json"):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return []

@st.cache_data
def load_topics(file_path="topics.json"):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

st.set_page_config(page_title="Copilot Intelligence Dashboard", layout="wide")
st.title("🧠 Copilot Chat Intelligence Dashboard")

chats = load_data()
topics = load_topics()

if not chats:
    st.warning("No chat data found. Please ensure all_chats_verified.json exists.")
    st.stop()

# Fast lookup for full chat data
chat_dict = {chat.get("id", chat.get("chat_id", "Unknown")): chat for chat in chats}

messages = []
for chat in chats:
    for msg in chat.get("messages", []):
        if msg.get("embedding"):
            messages.append({
                "chat_id": chat.get("id", chat.get("chat_id", "Unknown")),
                "url": chat.get("url", ""),
                "role": msg.get("role", "unknown"),
                "text": msg.get("text", ""),
                "embedding": np.array(msg["embedding"])
            })

st.sidebar.header("Overview")
st.sidebar.write(f"Total Chats: {len(chats)}")
st.sidebar.write(f"Total Messages: {len(messages)}")
if topics:
    st.sidebar.write(f"Total Topics: {len(topics)}")

tab1, tab2 = st.tabs(["📂 Topic Browser", "🔍 Semantic Search"])

with tab1:
    st.subheader("Topic Clusters")
    if not topics:
        st.info("No topic clusters found. Make sure topics.json was generated by the pipeline.")
    else:
        col1, col2 = st.columns([1, 2])
        
        with col1:
            cluster_names = list(topics.keys())
            selected_cluster = st.selectbox("Select a Topic Cluster", cluster_names)
            
            if selected_cluster:
                cluster_chats = topics[selected_cluster]
                st.write(f"**{len(cluster_chats)} chats** inside {selected_cluster}")
                
                chat_titles = [f"{c.get('title', 'Unknown')} ({c.get('messages_count', 0)} msgs)" for c in cluster_chats]
                selected_chat_title = st.selectbox("Select a Chat", chat_titles)
        
        with col2:
            if selected_cluster and selected_chat_title:
                idx = chat_titles.index(selected_chat_title)
                selected_chat_meta = cluster_chats[idx]
                chat_id = selected_chat_meta.get("chat_id")
                
                st.markdown(f"**Chat ID:** `{chat_id}`")
                st.markdown(f"**URL:** Open in Copilot")
                st.divider()
                
                full_chat = chat_dict.get(chat_id)
                if full_chat:
                    for msg in full_chat.get("messages", []):
                        with st.chat_message(msg.get("role", "user")):
                            st.write(msg.get("text", ""))
                else:
                    st.warning("Could not find the full message history for this chat in all_chats_verified.json.")

with tab2:
    st.subheader("Semantic Search")
    
    topic_options = ["All Topics"] + list(topics.keys()) if topics else ["All Topics"]
    selected_search_topic = st.selectbox("Filter by Topic (Optional)", topic_options)
    
    query = st.text_input("Ask a question against your chat history:")

    if query:
        model = load_model()
        query_vec = model.encode([query])[0]
        
        valid_chat_ids = None
        if selected_search_topic != "All Topics":
            valid_chat_ids = {meta.get("chat_id") for meta in topics.get(selected_search_topic, [])}
            
        scored = []
        for msg in messages:
            if valid_chat_ids is not None and msg["chat_id"] not in valid_chat_ids:
                continue
            score = np.dot(query_vec, msg["embedding"]) / (np.linalg.norm(query_vec) * np.linalg.norm(msg["embedding"]))
            scored.append((score, msg))
            
        scored.sort(key=lambda x: x[0], reverse=True)
        
        st.write(f"### Top Results {f'in {selected_search_topic}' if selected_search_topic != 'All Topics' else 'Across All Topics'}")
        if not scored:
            st.info("No matching messages found in the selected topic.")
        else:
            for score, msg in scored[:5]:
                with st.expander(f"**{msg['role'].upper()}** (Score: {score:.4f}) - Chat: {msg['chat_id']}"):
                    st.write(msg['text'])
                    st.markdown(f"[Go to Chat]({msg['url']})")